name: "AWS CodeArtifact login Action"
description: Github Action to fetch a token for AWS CodeArtifact and (optionally) retrieve a repository URL
inputs:
  domain:
    description: CodeArtifact domain to which the package repository belongs
    required: true
  domain-owner:
    description: Owner (AWS Account) of the CodeArtifact domain
    required: true
  repository:
    description: CodeArtifact repository for which to optionally fetch the URL
    required: true
  scope:
    description: Configure Poetry with temporary CodeArtifact credentials
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Configure package managers
      shell: bash
      run: |
        aws codeartifact login --tool npm --domain ${{ inputs.codeartifact-domain }} --domain-owner ${{ inputs.codeartifact-domain-owner }} --repository ${{ inputs.codeartifact-repository }} --namespace ${{ inputs.scope }}

