name: "AWS CodeArtifact login Action"
description: Github Action to fetch a token for AWS CodeArtifact and (optionally) retrieve a repository URL
inputs:
  domain:
    description: CodeArtifact domain to which the package repository belongs
    required: true
  accountId:
    description: Owner (AWS Account) of the CodeArtifact domain
    required: true
  repository:
    description: CodeArtifact repository for which to optionally fetch the URL
    required: true
  region:
    description: AWS Region
    required: false
    default: "us-east-1"
  scope:
    description: Configure tool with temporary CodeArtifact credentials
    required: false
    default: ""
  packageType:
    description: Tool Type
    required: false
    default: "npm"
runs:
  using: "composite"
  steps:
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
    - name: Configure package managers
      shell: bash
      run: |
        aws --version
        node -v
        aws codeartifact login --tool ${{ inputs.packageType }} --region ${{ inputs.region }} --domain ${{ inputs.domain }} --domain-owner ${{ inputs.accountId }} --repository ${{ inputs.repository }} --namespace ${{ inputs.scope }}

